### ISSUE TITLE
Game working

### ISSUE THREAD

**Issue by luizperes** [cornerstonecollege/janken_richmond#9]
Is there a way where I can see the game working? :D I'm very curious about!!! :)

@saeko0032, ask your new instructor if he is interested in sharing the @cornerstonecollege repository on github... if yes, I can add him on this repo or the others :)

**Comment by saeko0032** [comment]
Hi, Luiz! How are you doing?
I believe you can play it tomorrow. We will build a server :) (not a local one)

About @cornerstonecollege repository, I'll ask our new instructor tomorrow.

**Comment by luizperes** [comment]
I am doing well :) you?

Ok, I will be waiting! ;)

**Comment by luizperes** [comment]
Any updates?

**Comment by saeko0032** [comment]
Give us a minutes ;P

**Comment by ai230** [comment]
Hi Luiz. here is the address
https://janken.000webhostapp.com/
There are still some tasks we are going to change in "Projects" tab.

**Comment by luizperes** [comment]
Thank you @ai230 !
